"""empty message

Revision ID: c263b59c7459
Revises: f298dd46d0e3
Create Date: 2020-12-17 21:32:23.138860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c263b59c7459'
down_revision = 'f298dd46d0e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('image', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
